const data = [
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "22/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 40.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: true,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "21/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 43.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "20/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 56.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "19/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 60.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "27/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 56.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "19/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 43.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "26/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 40.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "17/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 56.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "20/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 41.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "16/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 56.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "15/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 47.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "26/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 56.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "21/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 59.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "A Nice Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "23/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 49.25,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
  {
    hospitalName: "The Best Hospital",
    addressStreet: "10 Nice Street",
    addressSuburb: "2000 NSW, Sydney",
    date: "22/04/2019",
    shiftStart: "07:00 AM",
    shiftEnd: "07:30 PM",
    hourlyRate: 59.65,
    hospitalDepartment: "Intensive Care General",
    rating: 5,
    invited: false,
  },
];

export default data;
